//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormularioCadastro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public int IdPaciente { get; set; }
        public string NomePaciente { get; set; }
        public int IdadePaciente { get; set; }
        public string EmailPaciente { get; set; }
        public string RespPaciente { get; set; }
        public Nullable<int> QuadroPaciente { get; set; }
    
        public virtual Quadro Quadro { get; set; }
    }
}
