//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormularioCadastro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public int IdProduto { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public int Preco { get; set; }
        public Nullable<int> Categoria { get; set; }
    
        public virtual Categoria Categoria1 { get; set; }
    }
}
